on:
  workflow_dispatch:
  #push:
  #  branches:
  #  - master
  #pull_request:
  #  branches:
  #  - master

name: ci_cuda_linux_self_hosted

jobs:
    build_cuda:
        name: CUDA
        runs-on: [self-hosted]
        env:
          CC: gcc
          CXX: g++
        strategy:
            fail-fast: false
        steps:
            - name: Checkout Repository
              uses: actions/checkout@master

            - name: CMake Configure
              env:
                  BLAS_BACKEND: OpenBLAS
              run: |
                  backend="FFTW/LAPACK/BLAS"
                  buildname="$buildname-cpu-$BLAS_BACKEND"
                  mkdir build && cd build
                  cmake -G Ninja \
                      -DCMAKE_MAKE_PROGRAM:FILEPATH=/usr/local/bin/ninja \
                      -DAF_BUILD_CUDA:BOOL=ON -DAF_BUILD_OPENCL:BOOL=OFF \
                      -DAF_BUILD_UNIFIED:BOOL=OFF -DAF_BUILD_EXAMPLES:BOOL=ON \
                      -DAF_BUILD_FORGE:BOOL=ON \
                      -DCUDA_architecture_build_targets:STRING="8.6"\
                      -DAF_COMPUTE_LIBRARY:STRING=${backend} \
                      -DBUILDNAME:STRING=${buildname} ..

            - name: Build
              run: |
                  cd build
                  ninja -j 12
