on:
  workflow_dispatch:
  #push:
  #  branches:
  #  - master
  #pull_request:
  #  branches:
  #  - master

name: ci_cuda_win

jobs:
    build_cuda:
        name: CUDA
        runs-on: windows-2022
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows
          CUDA_VER: 12.6.2
          CUDA_DRIVER: 560.94
        steps:
            - name: Checkout Repository
              uses: actions/checkout@master

            - name: Install CUDA for Windows
              run: |
                  curl -s "https://developer.download.nvidia.com/compute/cuda/$env:CUDA_VER/local_installers/cuda_$env:CUDA_VER_$env:CUDA_DRIVER_windows.exe"
                  .\cuda_$env:CUDA_VER_$env:CUDA_DRIVER_windows.exe -n -s nvcc_12.6 nvrtc_12.6 nvrtc_dev_12.6 `
                  thrust_12.6 opencl_12.6 cublas_12.6 cublas_dev_12.6 cufft_12.6 cufft_dev_12.6 curand_12.6 `
                  curand_dev_12.6 cusolver_12.6 cusolver_dev_12.6 cusparse_12.6 cusparse_dev_12.6 npp_12.6 `
                  npp_dev_12.6 nvjpeg_12.6 nvjpeg_dev_12.6 cudart_12.6

            - name: Install VCPKG Dependencies
              run: |
                pushd .
                cd ~
                git clone --quiet --recursive https://github.com/microsoft/vcpkg.git
                cd vcpkg
                git checkout 2024.09.30
                .\bootstrap-vcpkg.bat
                popd

            - name: CMake Configure
              run: |
                  $ref = $env:GITHUB_REF | %{ if ($_ -match "refs/pull/[0-9]+/merge") { $_;} }
                  $prnum = $ref | %{$_.Split("/")[2]}
                  $branch = git branch --show-current
                  $buildname = if($prnum -eq $null) { $branch } else { "PR-$prnum" }
                  $dashboard = if($prnum -eq $null) { "Continuous" } else { "Experimental" }
                  $buildname = "$buildname-cuda"
                  mkdir build && cd build && set VCPKG_ROOT=
                  cmake .. -G "Visual Studio 17 2022" -A x64 `
                      -DVCPKG_ROOT:PATH=~/vcpkg `
                      -DAF_BUILD_CUDA:BOOL=ON -DAF_BUILD_OPENCL:BOOL=OFF `
                      -DAF_BUILD_UNIFIED:BOOL=OFF -DAF_BUILD_FORGE:BOOL=ON `
                      -DAF_BUILD_EXAMPLES:BOOL=ON -DBUILDNAME:STRING="$buildname" `
                      -DAF_COMPUTE_LIBRARY:STRING="FFTW/LAPACK/BLAS"

            - name: Build and Test
              run: |
                  cd build
                  msbuild .\ArrayFire.sln -m2
