on:
  workflow_dispatch:
  #push:
  #  branches:
  #  - master
  #pull_request:
  #  branches:
  #  - master

name: ci_cuda_win

jobs:
    build_cuda:
        name: CUDA
        runs-on: windows-2022
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows
          CUDA_VER: 12.6.2
          CUDA_DRIVER: 560.94
        steps:
            - name: Install CUDA
            uses: Jimver/cuda-toolkit@v0.2.18
            id: cuda-toolkit
            with:
              cuda: '12.6.2'

            - name: Checkout Repository
              uses: actions/checkout@master

            - name: Install VCPKG Dependencies
              run: |
                nvcc -V
                pushd .
                cd ~
                git clone --quiet --recursive https://github.com/microsoft/vcpkg.git
                cd vcpkg
                git checkout 2024.09.30
                .\bootstrap-vcpkg.bat
                popd

            - name: CMake Configure
              run: |
                  $ref = $env:GITHUB_REF | %{ if ($_ -match "refs/pull/[0-9]+/merge") { $_;} }
                  $prnum = $ref | %{$_.Split("/")[2]}
                  $branch = git branch --show-current
                  $buildname = if($prnum -eq $null) { $branch } else { "PR-$prnum" }
                  $dashboard = if($prnum -eq $null) { "Continuous" } else { "Experimental" }
                  $buildname = "$buildname-cuda"
                  mkdir build && cd build && set VCPKG_ROOT=
                  echo $env:CUDA_TOOLKIT_ROOT_DIR
                  nvcc -V
                  cmake .. -G "Visual Studio 17 2022" -A x64 `
                      -DVCPKG_ROOT:PATH=~/vcpkg `
                      -DAF_BUILD_CUDA:BOOL=ON -DAF_BUILD_OPENCL:BOOL=OFF `
                      -DAF_BUILD_UNIFIED:BOOL=OFF -DAF_BUILD_FORGE:BOOL=ON `
                      -DAF_BUILD_EXAMPLES:BOOL=ON -DBUILDNAME:STRING="$buildname" `
                      -DAF_COMPUTE_LIBRARY:STRING="FFTW/LAPACK/BLAS"

            - name: Build and Test
              run: |
                  cd build
                  msbuild .\ArrayFire.sln -m2
